### PR TITLE
fix "Move to" button

### LINKED ISSUE #21: LionEngineException: Feature not found: RightClickMove
## Expected Behavior
Peon moves.

## Actual Behavior
Game crashes.

## Steps to Reproduce the Problem

1. Select peon.
2. Use "Move to" button.

## Specifications

  - Warcraft Remake Version: 0.0.3
  - JDK: 1.8
  - OS: Win10

### PR DESCRIPTION
**Pull request by SomeFire**
Fixes #21

### CODE REVIEW

**Comment by SomeFire** [comment]
If target point is forest - peon will be ordered to extract instead of move to closest position. I think it isn't expected behaviour for "Move to" order.

**Comment by DjThunder** [comment]
In the original game right click for Peon means Extract if possible, or move if nothing to extract.
For Grunt (and other attacker unit) it means Attack if target found (building or non friendly unit) or move else.
I'm working on wood extraction, so it will work later, as for GoldMine, should be fine.

**Comment by SomeFire** [comment]
I'm agree about right click, but I'm talking not about right click. I'm talking about move order, which is separated from extract.

**Comment by DjThunder** [comment]
Ah yes I see. I can't remember what's happening if clicking Move action over Wood or GoldMine. But as there is a dedicated action for Extract, it will be better to perform only a Move. Ok.
Linking Move action with RightClick action may create undesired action indeed.

**Pull request merged**
